package com.juarezln.testing.redisintegration.inventories.domain.model.entities;

import com.juarezln.testing.redisintegration.inventories.domain.model.aggregates.Product;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Stock {

    /**
     * The unique identifier for the stock entry. This field is typically generated by the database and should not be set manually when creating a new stock instance. It is marked with @Setter to allow setting the ID after the stock has been persisted.
     */
    private Long id;

    /**
     * The product associated with this stock entry. This field is required and should be set when creating a new stock instance. It is marked with @Setter to allow updating the associated product if necessary.
     */
    private Product product;

    /**
     * The quantity of the product available in stock. This field is required and should be set when creating a new stock instance. It is marked with @Setter to allow updating the quantity as inventory levels change.
     */
    private Integer quantity;

    public Stock() {
        // Default constructor for frameworks that require it
    }

    /**
     * Constructor for creating a new Stock instance with the specified product and quantity. The ID is not included in the constructor parameters as it is typically generated by the database when the stock entry is persisted.
     *
     * @param product the product associated with this stock entry
     * @param quantity the quantity of the product available in stock
     */
    public Stock(Product product, Integer quantity) {
        this.product = product;
        this.quantity = quantity;
    }

    /**
     * Increases the quantity of the product in stock by the specified amount. This method takes an integer parameter representing the amount to increase the stock quantity by and adds it to the current quantity, allowing for easy updates to inventory levels when new stock is added.
     *
     * @param amount the amount to increase the stock quantity by
     */
    public void increaseQuantity(Integer amount) {
        this.quantity += amount;
    }

    /**
     * Decreases the quantity of the product in stock by the specified amount. This method checks if the resulting quantity would be negative and throws an IllegalArgumentException if it is, ensuring that the stock quantity cannot go below zero.
     *
     * @param amount the amount to decrease the stock quantity by
     */
    public void decreaseQuantity(Integer amount) {
        if (this.quantity - amount < 0) {
            throw new IllegalArgumentException("Cannot decrease quantity below zero.");
        }
        this.quantity -= amount;
    }
}
