package com.juarezln.testing.redisintegration.shared.infrastructure.persistence.jpa.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.util.Date;

/**
 * Base JPA class for entities that require auditing of creation and modification timestamps.
 * This class is annotated with @MappedSuperclass, indicating that it is a superclass for JPA entities and its properties will be inherited by subclasses. The @EntityListeners(AuditingEntityListener.class) annotation enables the auditing functionality provided by Spring Data JPA, allowing automatic population of the createdAt and updatedAt fields when entities are persisted and updated.
 */
@Getter
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class AuditableAbstractPersistenceEntity {

    /**
     * The unique identifier for the entity.
     * This field is annotated with @Id to indicate that it is the primary key of the entity, and @GeneratedValue with strategy = GenerationType.IDENTITY to specify that the value should be automatically generated by the database using an identity column. The @Setter annotation from Lombok allows for setting the value of this field, although in practice, it is typically managed by the persistence framework and should not be manually set in application code.
     */
    @Setter
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The date and time when the entity was created. This field is automatically populated by Spring Data JPA
     * when the entity is first persisted. It is annotated with @CreatedDate to indicate that it should be automatically managed by the auditing framework. The column is marked as non-nullable and not updatable to ensure that it always contains a value and cannot be modified after creation.
     */
    @CreatedDate
    @Column(nullable = false, updatable = false)
    private Date createdAt;

    /**
     * The date and time when the entity was last modified. This field is automatically updated by Spring Data JPA
     * whenever the entity is updated. It is annotated with @LastModifiedDate to indicate that it should be automatically managed by the auditing framework. The column is marked as non-nullable to ensure that it always contains a value, and it is not updatable to prevent manual changes to this field
     */
    @LastModifiedDate
    @Column(nullable = false)
    private Date updatedAt;
}
