package com.juarezln.testing.redisintegration.inventories.domain.model.aggregates;

import com.juarezln.testing.redisintegration.inventories.domain.model.commands.RegisterProductCommand;
import com.juarezln.testing.redisintegration.shared.domain.model.valueobjects.Money;
import lombok.Getter;
import lombok.Setter;

/**
 * This class is an aggregate root that encapsulates the product's properties and behaviors.
 * It includes attributes such as name, description, and price, and provides methods to update the product's price. The class uses Lombok annotations to generate getters and setters for its fields, simplifying the code and improving readability.
 *
 * @summary Represents a product in the inventory system.
 */
@Getter
@Setter
public class Product {

    /**
     * The unique identifier for the product. This field is typically generated by the database and should not be set manually when creating a new product instance. It is marked with @Setter to allow setting the ID after the product has been persisted.
     */
    private Long id;

    /**
     * The name of the product. This field is required and should be set when creating a new product instance. It is marked with @Setter to allow updating the product's name if necessary.
     */
    private String name;

    /**
     * A brief description of the product. This field is optional and can be set when creating a new product instance or updated later. It is marked with @Setter to allow modifying the product's description as needed.
     */
    private String description;

    /**
     * The price of the product. This field is required and should be set when creating a new product instance. It is marked with @Setter to allow updating the product's price through the updatePrice method or directly if necessary.
     */
    private Money price;

    /**
     * Constructor for creating a new Product instance with the specified name, description, and price. The ID is not included in the constructor parameters as it is typically generated by the database when the product is persisted.
     *
     * @param name the name of the product
     * @param description a brief description of the product
     * @param price the price of the product
     */
    public Product(String name, String description, Money price) {
        this.name = name;
        this.description = description;
        this.price = price;
    }

    /**
     * Constructor for creating a new Product instance using a RegisterProductCommand. This constructor allows for easy creation of a Product object from the command object, which encapsulates the necessary information for registering a new product. The ID is not included in the constructor parameters as it is typically generated by the database when the product is persisted.
     *
     * @param command the RegisterProductCommand containing the information needed to create a new Product instance, including the name, description, and price of the product. The constructor extracts these values from the command object and initializes the corresponding fields in the Product instance.
     */
    public Product(RegisterProductCommand command) {
        this.name = command.name();
        this.description = command.description();
        this.price = command.price();
    }

    /**
     * Updates the price of the product. This method allows changing the product's price after it has been created. It takes a Money object as a parameter, which represents the new price to be set for the product.
     *
     * @param newPrice the new price to be set for the product
     */
    public void updatePrice(Money newPrice) {
        this.price = newPrice;
    }
}
