package com.juarezln.testing.redisintegration.inventories.infrastructure.persistence.jpa.assemblers;

import com.juarezln.testing.redisintegration.inventories.domain.model.aggregates.Product;
import com.juarezln.testing.redisintegration.inventories.infrastructure.persistence.jpa.entities.ProductPersistenceEntity;

/**
 * This class is responsible for converting between Product domain objects and ProductPersistenceEntity objects. It provides static methods to facilitate the transformation of data between the domain model and the persistence layer, ensuring that the application can seamlessly interact with the database while maintaining a clear separation of concerns. The assembler handles the mapping of properties such as ID, name, description, and price between the two representations of a product.
 */
public final class ProductPersistenceAssembler {

    private ProductPersistenceAssembler() {
        // Private constructor to prevent instantiation
    }

    /**
     * Converts a ProductPersistenceEntity to a Product domain object. This method takes a ProductPersistenceEntity, which is typically retrieved from the database, and creates a corresponding Product domain object by copying the relevant properties such as ID, name, description, and price. If the input entity is null, the method returns null.
     *
     * @param entity the ProductPersistenceEntity to be converted to a Product domain object. This entity contains the properties of the product as stored in the database, including the ID, name, description, and price. The method will create a new Product instance and populate its fields based on the values from the provided entity.
     * @return a Product domain object that represents the provided ProductPersistenceEntity, ready for use in the application. If the input entity is null, the method will return null.
     */
    public static Product toDomainFromPersistence(ProductPersistenceEntity entity) {
        if (entity == null) return null;

        var product = new Product();
        product.setId(entity.getId());
        product.setName(entity.getName());
        product.setDescription(entity.getDescription());
        product.setPrice(entity.getPrice());

        return product;
    }

    /**
     * Converts a Product domain object to a ProductPersistenceEntity for persistence. If the product's ID is null, it will not be set on the entity, allowing the database to generate it for new products. If the product's ID is not null, it will be included in the entity, which is useful for updating existing products.
     *
     * @param product the Product domain object to be converted to a ProductPersistenceEntity. This object contains the product's properties such as name, description, price, and optionally the ID if it has been set. The method will create a new ProductPersistenceEntity and populate its fields based on the properties of the provided Product object.
     * @return a ProductPersistenceEntity that represents the provided Product domain object, ready for persistence in the database. If the input product is null, the method will return null.
     */
    public static ProductPersistenceEntity toPersistenceFromDomain(Product product) {
        if (product == null) return null;

        var entity = new ProductPersistenceEntity();

        // Only set the ID if it's not null, as it should be generated by the database for new products
        if (product.getId() != null) {
            entity.setId(product.getId());
        }
        entity.setName(product.getName());
        entity.setDescription(product.getDescription());
        entity.setPrice(product.getPrice());

        return entity;
    }
}
