package com.juarezln.testing.redisintegration.inventories.interfaces.rest.resources;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * This class is a record that represents a product item resource in the inventory system. It includes fields for the product's ID, name, description, and price details (money amount and currency code). The class is annotated with @Schema to provide metadata for API documentation, describing the purpose of each field and the overall resource. This resource is used for transferring product information between the client and server in RESTful API interactions.
 *
 * @param id The unique identifier of the product item. This field is typically generated by the database and is used to uniquely identify each product item in the inventory system.
 * @param name The name of the product item. This field is required and should be provided when creating a new product item or updating an existing one.
 * @param description A brief description of the product item. This field is optional and can be provided to give more details about the product item.
 * @param moneyAmount The amount of money representing the price of the product item. This field is required and should be provided when creating a new product item or updating an existing one. It represents the numerical value of the price.
 * @param moneyCurrencyCode The currency code for the price of the product item. This field is required and should be provided when creating a new product item or updating an existing one. It represents the currency in which the price is denominated, such as USD for US dollars, EUR for euros, etc.
 */
@Schema(
        name = "ProductItemResource",
        description = "Represents a product item in the inventory system, including its ID, name, description, and price details. This resource is used for transferring product information between the client and server in RESTful API interactions."
)
public record ProductResource(
        @Schema(
                description = "The unique identifier of the product item. This field is typically generated by the database and is used to uniquely identify each product item in the inventory system."
        )
        Long id,

        @Schema(
                description = "The name of the product item. This field is required and should be provided when creating a new product item or updating an existing one."
        )
        String name,

        @Schema(
                description = "A brief description of the product item. This field is optional and can be provided to give more details about the product item."
        )
        String description,

        @Schema(
                description = "The amount of money representing the price of the product item. This field is required and should be provided when creating a new product item or updating an existing one. It represents the numerical value of the price."
        )
        Double moneyAmount,

        @Schema(
                description = "The currency code for the price of the product item. This field is required and should be provided when creating a new product item or updating an existing one. It represents the currency in which the price is denominated, such as USD for US dollars, EUR for euros, etc."
        )
        String moneyCurrencyCode
) {
}
