package com.juarezln.testing.redisintegration.shared.infrastructure.persistence.redis.entities;

import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;

/**
 * Abstract base class for persistence entities in Redis.
 * This class provides a common structure for all Redis entities by defining an 'id' field that serves as the unique identifier for each entity. The 'id' field is annotated with @Id to indicate that it is the primary key for the entity, and it has getter and setter methods generated by Lombok annotations.
 *
 * @version 1.0.0
 */
@Getter
public abstract class AbstractPersistenceEntity {

    /**
     * The unique identifier for the entity.
     * This field is annotated with @Id to indicate that it is the primary key for the Redis entity. The setter method allows for setting the value of 'id', while the getter method allows for retrieving its value.
     */
    @Id
    @Setter
    private String id;
}
